### ISSUE TITLE
Improve the date column in Active editors report

### ISSUE THREAD

**Issue by Niharika29** [Niharika29/database-reports#23]
The date column in https://en.wikipedia.org/wiki/Wikipedia:Database_reports/Active_editors_with_the_longest-established_accounts this report prints the string in the db table, without pretty-fying it. It should be made more readable.

**Comment by Niharika29** [comment]
CC @srish

**Comment by mzmcbride** [comment]
Something like this might be nice:

```
>>> datetime.datetime.strptime('20010327204731', '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H:%M:%S')
'2001-03-27 20:47:31'
```

**Comment by ritikBhandari** [comment]
Is this issue still open?
I would like to work on this if possible.

**Comment by MusikAnimal** [comment]
Yes! This one is up for grabs if you'd like to work on it :) Thank you!

**Comment by ritikBhandari** [comment]
Sure. Thanks :)

**Comment by ritikBhandari** [comment]
But why isn't this issue resolved yet? Like, its been 4 years!

**Comment by MusikAnimal** [comment]
4 years isn't that long in the wiki world :) This is a pretty easy issue to fix, though. Speaking for Community Tech (the WMF team that maintains this repo), we haven't actively worked on this for years. We generally use [Phabricator](https://phabricator.wikimedia.org/) to track software improvements and bug reports, so I don't think anyone has reviewed the issues here on GitHub in a long while.

**Comment by ritikBhandari** [comment]
So if I want to contribute consistently to Wikimedia, should I continue on Github or switch to Phabricator?

**Comment by theresnotime** [comment]
> So if I want to contribute consistently to Wikimedia, should I continue on Github or switch to Phabricator?

It'd definitely be worth getting familiar with [phabricator](https://www.mediawiki.org/wiki/Phabricator) — [this page](https://www.mediawiki.org/wiki/New_Developers#Welcome!) is a good place to start 😃

**Comment by MusikAnimal** [comment]
Yeah, most development actually happens on [Gerrit](https://www.mediawiki.org/wiki/Gerrit) and is only mirrored on GitHub. We use Phabricator to track issues. This repository is an exception and happens to live here on GitHub. We should probably close the Issues and force users to Phabricator (though we don't yet have a tag for this project).

**Comment by ritikBhandari** [comment]
Why does Wikimedia use Phabricator and not Github?

**Comment by MusikAnimal** [comment]
> Why does Wikimedia use Phabricator and not Github?

GitHub is not very full-featured when it comes to bug tracking. In an ecosystem as large as Wikimedia, it simply doesn't meet our needs. Furthermore, GitHub is closed source when we strive to use opensource software where possible.

**Comment by ritikBhandari** [comment]
@MusikAnimal is there any particular language(s) that Wikimedia uses for its major projects? I'm new to Gerrit and Phabricator ecosystem and it'll take time to understand how things work out.

**Comment by MusikAnimal** [comment]
> @MusikAnimal is there any particular language(s) that Wikimedia uses for its major projects? I'm new to Gerrit and Phabricator ecosystem and it'll take time to understand how things work out.

[MediaWiki itself](https://www.mediawiki.org/wiki/How_to_become_a_MediaWiki_hacker) is mostly PHP, but there are hundreds of projects to contribute to under the Wikimedia umbrella that use a wide range of technologies. Here are some links to help you get started:
* https://www.mediawiki.org/wiki/New_Developers – high level overview for all new contributors
* https://www.mediawiki.org/wiki/How_to_become_a_MediaWiki_hacker – basics you need to contribute to MediaWiki and its extensions (PHP/JavaScript mostly)
* https://phabricator.wikimedia.org/maniphest/query/jsySdXllltwv/ – tasks marked on Phabricator as "good first tasks". The blue boxes below each title denote the project.
* https://www.mediawiki.org/wiki/How_to_contribute – other ways to contribute

You may also be interested in our upcoming [Wikimedia Hackathon 2022](https://www.mediawiki.org/wiki/Wikimedia_Hackathon_2022) from May 20–22. All newcomers are welcome, and it's happening virtually and at [in-person events](https://www.mediawiki.org/wiki/Wikimedia_Hackathon_2022/Meetups) around the world! I highly recommend checking this out :)

Hope this helps, and thanks again for contributing!

**Comment by ritikBhandari** [comment]
Thanks @MusikAnimal for the guidance. Really appreciate it.
