### ISSUE TITLE
Links to Sigma's pages created tool are broken if there are spaces in the username

### ISSUE THREAD

**Issue by Niharika29** [Niharika29/database-reports#3]
Steps to reproduce:
1. Go to https://en.wikipedia.org/wiki/Wikipedia:Database_reports/Editors_eligible_for_Autopatrol_privilege
2. Click on '(list)' link for a user having spaces in username.
3. No results are shown because the space is converted into an underscore i.e. "John Smith" changes into "John_Smith"

**Comment by arafed** [comment]
Resolved by `REPLACE (user_name," ","%20")`
