### ISSUE TITLE
DBR on kowiki misbehaving

### ISSUE THREAD

**Issue by revi** [Niharika29/database-reports#30]
https://ko.wikipedia.org/wiki/위키백과:데이터베이스_보고서/지난_달에_가장_많이_편집된_문서

Doesn't sound quite right.

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/7630875/63249477-d1e04000-c269-11e9-9ef6-b5a11119f8cb.png">

**Comment by MaxSem** [comment]
Fixed in https://phabricator.wikimedia.org/T230738
